version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testDB
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5431:5432"
    restart: always
