/*
 * This file is generated by jOOQ.
 */
package com.gmail.geraldik.newsfeed.pesristence.tables.records;


import com.gmail.geraldik.newsfeed.pesristence.tables.Item;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Created news
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record5<Integer, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item.id</code>. News id
     */
    public ItemRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.item.id</code>. News id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.item.title</code>. Title of the news 
     */
    public ItemRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.item.title</code>. Title of the news 
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.item.body</code>. News text
     */
    public ItemRecord setBody(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.item.body</code>. News text
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item.author</code>. News author
     */
    public ItemRecord setAuthor(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.item.author</code>. News author
     */
    public String getAuthor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.item.created</code>. News creation date (UTC+0)
     */
    public ItemRecord setCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.item.created</code>. News creation date (UTC+0)
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Item.ITEM.ID;
    }

    @Override
    public Field<String> field2() {
        return Item.ITEM.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Item.ITEM.BODY;
    }

    @Override
    public Field<String> field4() {
        return Item.ITEM.AUTHOR;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Item.ITEM.CREATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getBody();
    }

    @Override
    public String component4() {
        return getAuthor();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getBody();
    }

    @Override
    public String value4() {
        return getAuthor();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public ItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ItemRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ItemRecord value3(String value) {
        setBody(value);
        return this;
    }

    @Override
    public ItemRecord value4(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public ItemRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ItemRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Integer id, String title, String body, String author, LocalDateTime created) {
        super(Item.ITEM);

        setId(id);
        setTitle(title);
        setBody(body);
        setAuthor(author);
        setCreated(created);
    }
}
