/*
 * This file is generated by jOOQ.
 */
package com.gmail.geraldik.newsfeed.pesristence;


import com.gmail.geraldik.newsfeed.pesristence.tables.Comment;
import com.gmail.geraldik.newsfeed.pesristence.tables.Item;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Комментарий к новости
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * Создаваемая новость
     */
    public static final Item ITEM = Item.ITEM;
}
